
services:
  database:
    image: mysql
    env_file: ./src/backend/.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

