name: gitalytics

services:
#  frontend:
#    build: ./src/frontend
#
#  fastapi-server:
#    build: ./src/backend
#    ports:
#      - "8000:8000" # change internal port to 60860 (random port))
#    depends_on:
#      database:
#        condition: service_healthy
#      frontend:
#        condition: service_completed_successfully

  database:
    image: mysql
    env_file: ./src/backend/.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

